### PR TITLE
Improves code coverage for #23

### PR DESCRIPTION
**Pull request by tilmanpotthof**
- removes dead code
- improves json schema

### CODE REVIEW

**Comment by tilmanpotthof** [comment]
The regex in the json schema does not cover all possible combinations of ACEM, but it think almost nobody uses C and M and the combinations 'AE' and 'EA' are covered.

**Comment by remcohaszing** [comment]
Perhaps this option should be removed entirely. I think using `C` or `M` is never a good idea. In that case the rule would just check for the `AE` restriction and the explicitness of the default.

**Comment by tilmanpotthof** [comment]
Yes, good point. M is not documented anymore since 1.2 and I guess it was also removed (didn't checked that). C is not recommended and we can refer to https://github.com/johnpapa/angular-styleguide#style-y074

**Comment by tilmanpotthof** [comment]
I removed the options and modified the test cases. I also added another test case to see if a wrong restrict order gets reported. With this test case I saw that a wrong restrict property gets also reported as missing, because it is not removed from the unchecked array. I fixed that, too.

**Pull request merged**
